version: '3.8'

services:
  fastapi:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    ports:
      - "${FASTAPI_PORT}:8000"
    volumes:
      - ./models:/models
      - ./data:/data
      - ./logs:/logs
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - prometheus

  streamlit:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - "${STREAMLIT_PORT}:8501"
    volumes:
      - ./models:/models
      - ./logs:/logs
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=${API_URL}

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - prometheus

  kuma:
    image: louislam/uptime-kuma:1
    ports:
      - "${KUMA_PORT}:3001"
    volumes:
      - ./uptime-kuma:/app/data
    restart: unless-stopped

  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    container_name: prefect-server
    ports:
      - "4200:4200"
    volumes:
      - prefect_data:/root/.prefect
    environment:
      - PREFECT_LOGGING_LEVEL=INFO
      - PREFECT_ORION_API_HOST=0.0.0.0
    restart: unless-stopped

  training-flow:
    build:
      context: ./prefect_flows
      dockerfile: Dockerfile
    depends_on:
      - prefect-server
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    command: python training_flow.py

  prefect-worker:
    image: prefecthq/prefect:3-latest
    depends_on:
      - prefect-server
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    command: prefect worker start --pool default-agent-pool

volumes:
  logs:
  models:
  data:
  prefect_data:
